//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saleinfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string contact_no { get; set; }
        public string contact_email { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string car_model { get; set; }
        public string car_make { get; set; }
        public string car_year { get; set; }
    }
}
